version: '3.9'

services:
  simulation:
    build:
      dockerfile: ./simulation.Dockerfile
    user: docker
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_DOMAIN_ID=100
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: /bin/bash -c \
              "export TURTLEBOT3_MODEL=waffle \
              && ros2 launch nav2_bringup tb3_simulation_launch.py headless:=False"
